server:
   port: 9300
spring:
   application:
      name: medtech-service
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://eureka-server:8761/eureka/         
         
      
message:
  not_found: Khong tim thay
