server:
   port: 9300
spring:
   application:
      name: medtech-service
   datasource:
      url: jdbc:oracle:thin:@172.16.19.115:1521:orcl       
      username: medcenter   
      password: ENC(Ls2gKgkX4cgkK0KumiFTUfA7oxED82tU)
      driverClassName: oracle.jdbc.OracleDriver 
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://eureka-server:8761/eureka/         
         
      
ngochai:
  name: haiha2
