server:
   port: 8762
   
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://eureka-server:8761/eureka/

spring:
  application:
      name: zuul-server
